export const Config = {
    // WIND SPEED
    NORTH_WIND_SPEED: 0.01,
    SOUTH_WIND_SPEED: 0.01,
    EAST_WIND_SPEED: 0.01,
    WEST_WIND_SPEED: 0.01,

    // PENALTY DURATION
    PENALTY_TIME: 5,

    // OBJECT TIME OUT DURATION
    OBJECT_TIMED_OUT: 6,

    // TRACK WIDTH
    TRACK_WIDTH: 2.5,

    // TIME LIMIT
    TIME_LIMIT: 420,

    // DISPLAY DELAY
    DISPLAY_DELAY: 60,

    // LOD DISTANCE
    LOD_DISTANCE: 60
};